name: 'Webhook Github Action'
description: 'Webhook Github Action'
inputs:
  webhook_url:
    description: 'URL of the Webhook'
    required: true
  headers:
    description: 'JSON Headers of the request'
    required: false
  method:
    description: 'Method for the REST Webhook call'
    required: false
  body:
    description: 'JSON body for the REST Webhook call in case of POST, PUT, PATCH methods'
    required: false

runs:
  using: 'node12'
  main: 'build/index.js'
